export default {
  GET_PACKETS: "GET_PACKETS",
  SET_PACKETS: "SET_PACKETS",
  RESET_PACKETS: "RESET_PACKETS",
  GET_CONNECTIONS: "GET_CONNECTIONS",
  SET_CONNECTIONS: "SET_CONNECTIONS",
  RESET_CONNECTIONS: "RESET_CONNECTIONS"
};